services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment: 
      - MONGODB_URI=mongodb://mongodb:27017/todos
      - AWS_ACCESS_KEY_ID=< PUT YOUR OWN AWS ACCESS KEY HERE >
      - AWS_SECRET_ACCESS_KEY=< PUT YOUR OWN AWS SECRET ACCESS KEY HERE >
      - S3_BUCKET_NAME=image-gallery-test-bucket
      - AWS_REGION=us-east-1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          VITE_BACKEND_ENDPOINT: http://localhost:5000
          VITE_SERVER_HOSTNAME: ${HOSTNAME}
    ports:
      - 3000:3000
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodbdata:

