services:
  frontend:
    image: deniesemillanes/frontend-app:latest
    ports:
      - 3000:3000
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - webnet

networks:
  webnet: